[project]
name = "novel"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "apscheduler>=3.11.0",
    "curl-cffi>=0.11.4",
    "fastapi>=0.115.14",
    "lxml>=6.0.0",
    "uvicorn>=0.35.0",
]
