name: Docker

inputs:
    DOCKER_HUB_USERNAME: 
        description: "DOCKER HUB USERNAME"
        required: true
    DOCKER_HUB_TOKEN: 
        description: "DOCKER HUB TOKEN"
        required: true

runs:
    using: 'composite'

    steps:
        -   name: Set up QEMU
            uses: docker/setup-qemu-action@v3

        -   name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3

        -   name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
                username: ${{ inputs.DOCKER_HUB_USERNAME }}
                password: ${{ inputs.DOCKER_HUB_TOKEN }}