name: Docker

inputs:
  REGISTRY_ADDRESS:
    description: "REGISTRY ADDRESS TO STORE IMAGE"
    required: true
  REGISTRY_USERNAME: 
    description: "REGISTRY USERNAME"
    required: true
  REGISTRY_PASSWORD: 
    description: "REGISTRY PASSWORD"
    required: true
  REGISTRY_NAME_SPACE: 
    description: "REGISTRY NAME SPACE"
    required: true
  DOCKER_BUILD_NAME: 
    description: "DOCKER BUILD NAME"
    required: true
  DOCKER_BUILD_PATH: 
    description: "DOCKER BUILD PATH"
    required: true
  DOCKER_BUILD_TAG: 
    description: "DOCKER BUILD TAG"
    required: true
  DOCKER_BUILD_PLATFORMS: 
    description: "DOCKER BUILD PLATFORMS"
    default: 'linux/amd64, linux/arm64'

runs:
  using: "composite"

  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to image registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.REGISTRY_ADDRESS }}
        username: ${{ inputs.REGISTRY_USERNAME }}
        password: ${{ inputs.REGISTRY_PASSWORD }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.REGISTRY_NAME_SPACE }}/${{ inputs.DOCKER_BUILD_NAME }}
        tags: ${{ inputs.DOCKER_BUILD_TAG }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.DOCKER_BUILD_PATH }}
        push: true
        platforms: ${{ inputs.DOCKER_BUILD_PLATFORMS }}
        tags: ${{ steps.meta.outputs.tags }}