name: Docker

inputs:
    DOCKER_HUB_USERNAME: 
        description: "DOCKER HUB USERNAME"
        required: true
    DOCKER_HUB_TOKEN: 
        description: "DOCKER HUB TOKEN"
        required: true
    DOCKER_BUILD_NAME: 
        description: "DOCKER BUILD NAME"
        required: true
    DOCKER_BUILD_PATH: 
        description: "DOCKER BUILD PATH"
        required: true
    DOCKER_BUILD_TAG: 
        description: "DOCKER BUILD TAG"
        default: 'latest'
    DOCKER_BUILD_PLATFORMS: 
        description: "DOCKER BUILD PLATFORMS"
        default: 'linux/amd64, linux/arm64/v8'

runs:
    using: 'composite'

    steps:
        -   name: Set up QEMU
            uses: docker/setup-qemu-action@v3

        -   name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3

        -   name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
                username: ${{ inputs.DOCKER_HUB_USERNAME }}
                password: ${{ inputs.DOCKER_HUB_TOKEN }}

        -   name: Docker meta
            id: meta
            uses: docker/metadata-action@v5
            with:
                images: ${{ inputs.DOCKER_HUB_USERNAME }}/${{ inputs.DOCKER_BUILD_NAME }}
                tags: ${{ inputs.DOCKER_BUILD_TAG }}

        -   name: Build and push
            uses: docker/build-push-action@v5
            with:
                context: ${{ inputs.DOCKER_BUILD_PATH }}
                push: true
                platforms: ${{ inputs.DOCKER_BUILD_PLATFORMS }}
                tags: ${{ steps.meta.outputs.tags }}