name: Docker

inputs:
  REGISTRY_ADDRESS:
    description: "Registry address"
    default: "docker.io"
  REGISTRY_USERNAME: 
    description: "Registry username"
    default: "sgrtye"
  REGISTRY_PASSWORD: 
    description: "Registry password"
    required: true
  DOCKER_BUILD_NAME: 
    description: "Docker build name"
    required: true
  DOCKER_BUILD_PATH: 
    description: "Docker build path"
    required: true
  DOCKER_BUILD_TAG: 
    description: "Docker build tag"
    default: "latest"
  DOCKER_BUILD_PLATFORMS: 
    description: "Docker build platforms"
    default: "linux/amd64, linux/arm64"
  DRY_RUN:
    description: "Build image without pushing"
    required: true

runs:
  using: "composite"

  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to image registry
      uses: docker/login-action@v3
      if: ${{ inputs.DRY_RUN != 'true' }}
      with:
        registry: ${{ inputs.REGISTRY_ADDRESS }}
        username: ${{ inputs.REGISTRY_USERNAME }}
        password: ${{ inputs.REGISTRY_PASSWORD }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.REGISTRY_USERNAME }}/${{ inputs.DOCKER_BUILD_NAME }}
        tags: ${{ inputs.DOCKER_BUILD_TAG }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.DOCKER_BUILD_PATH }}
        push: ${{ inputs.DRY_RUN != 'true' }}
        platforms: ${{ inputs.DOCKER_BUILD_PLATFORMS }}
        tags: ${{ steps.meta.outputs.tags }}