name: OCI build

on:
  push:
    paths:
      - "oci/**"
  workflow_dispatch:

jobs:
  OCI:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true

      - name: Build and push to Docker Hub
        uses: ./.github/actions/Docker
        with:
          REGISTRY_PASSWORD: ${{ secrets.DOCKER_HUB_TOKEN }}
          DOCKER_BUILD_NAME: "oci"
          DOCKER_BUILD_PATH: "./oci"
          DOCKER_BUILD_TAG: ${{ github.ref_name == 'main' && 'latest' || 'dev' }}