name: Submanager build

on:
  push:
    paths:
      - 'submanager/**'
  workflow_dispatch:

jobs:
  Submanager:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Build and push to Docker Hub
        uses: ./.github/actions/Docker
        with:
          REGISTRY_ADDRESS: ${{ secrets.DOCKER_HUB_ADDRESS }}
          REGISTRY_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.DOCKER_HUB_TOKEN }}
          REGISTRY_NAME_SPACE: ${{ secrets.DOCKER_HUB_NAME_SPACE }}
          DOCKER_BUILD_NAME: 'submanager'
          DOCKER_BUILD_PATH: './submanager'