name: APIServer build

on:
  push:
    paths:
      - "apiserver/**"
  workflow_dispatch:

jobs:
  APIServer:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v5

      - name: Build and push to Docker Hub
        uses: ./.github/actions/Docker
        with:
          REGISTRY_PASSWORD: ${{ secrets.DOCKER_HUB_TOKEN }}
          DOCKER_BUILD_NAME: "apiserver"
          DOCKER_BUILD_PATH: "./apiserver"
          DRY_RUN: ${{ github.actor == 'dependabot[bot]' }}