name: Telebot build

on:
    push:
        paths:
            -   './telebot'
    workflow_dispatch:

jobs:
    Telebot:
        runs-on: ${{ vars.SYSTEM }}
        timeout-minutes: ${{ fromJSON(vars.TIMEOUT) }}

        steps:
            -   uses: actions/checkout@v4

            -   name: Set up docker build environment
                uses: ./.github/actions/Docker
                with:
                    DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
                    DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}

            -   name: Docker meta
                id: meta
                uses: docker/metadata-action@v5
                with:
                    images: ${{ secrets.DOCKER_HUB_USERNAME }}/telebot
                    tags: latest

            -   name: Build and push
                uses: docker/build-push-action@v5
                with:
                    context: ./telebot
                    push: true
                    platforms: linux/amd64, linux/arm64/v8
                    tags: ${{ steps.meta.outputs.tags }}